# SPDX-FileCopyrightText: 2024 Christopher Claus Holst
#
# SPDX-License-Identifier: CC-BY-4.0

version = 1

[[annotations]]
path = [
  "ISSUE_TEMPLATE/*",
  "workflows/*",
  "dependabot.yml"
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Christopher Claus Holst, KIT"
SPDX-License-Identifier = "CC-BY-4.0"
