# SPDX-FileCopyrightText: 2024 Christopher Claus Holst
#
# SPDX-License-Identifier: CC-BY-4.0

version = 1

[[annotations]]
path = ["*.yml"
        "assets/*.png"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Christopher C. Holst, KIT"
SPDX-License-Identifier = "CC-BY-4.0"
