# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ruff lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.6"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f REQUIREMENTS.txt ]; then pip install -r REQUIREMENTS.txt; fi

    - name: Lint with ruff
      run: |
        pip install ruff
        ruff check tool/*.py
        ruff check tests/*.py
